services:
  php:
    image: tugboatqa/php:8.0.14-apache
    default: true
    depends: mysql
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - ln -snf $TUGBOAT_ROOT $DOCROOT
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush
        - echo "memory_limit = 2G" >> /usr/local/etc/php/conf.d/my-php.ini
      update:
        - sed -i "s/self\.version/${TUGBOAT_GITLAB_TARGET:-$TUGBOAT_PREVIEW}/g" composer.json
        - composer install --optimize-autoloader
        - composer require drush/drush:11.0.0-rc7
        - mkdir -p "${DOCROOT}/sites/default/files"
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;
        - drush --yes --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat --account-name=admin --account-pass=admin site:install standard
      build:
        - sed -i "s/self\.version/${TUGBOAT_GITLAB_TARGET:-$TUGBOAT_PREVIEW}/g" composer.json
        - composer install --optimize-autoloader
        - composer require drush/drush:11.0.0-rc7
        - drush updatedb -y
        - drush cache:rebuild
  mysql:
    image: tugboatqa/mariadb:10
