services:
  php73:
    image: tugboatqa/php:7.3-apache
    default: true
    depends:
      - mysql
    commands:
      init:
        - sed -i 's/self\.version/~8\.8\.0/g' composer.json
        - a2enmod headers rewrite
        - docker-php-ext-install opcache
        - ln -snf $TUGBOAT_ROOT $DOCROOT
      update:
        - composer install --optimize-autoloader
        - composer require drush/drush
        - mkdir -p sites/default/files
        - chgrp -R www-data sites/default/files
        - chmod 2775 sites/default/files
        - chmod -R g+w sites/default/files
        - vendor/bin/drush --yes --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat --account-name=admin --account-pass=tugboat site:install standard
      build:
        - composer install --optimize-autoloader
        - composer require drush/drush
        - vendor/bin/drush updb
        - vendor/bin/drush cache:rebuild
    visualdiffs:
      - /
      - /node
      - /user/login
      - /contact
  mysql:
    image: tugboatqa/mariadb:10